site_name: Jacky's Note
theme:
  favicon: LocalFile/favicon.svg
  logo: LocalFile/favicon.svg
  palette: 
    primary: custom
  font:
    text: STSong
    code: Consolas
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.select
  language: zh
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - 数据库:
    - "MySQL":
      - DataBase/MySQL/MySQL Tips.md
      - DataBase/MySQL/MySQL 变量.md
      - DataBase/MySQL/MySQL 安装.md
      - DataBase/MySQL/MySQL 备份.md
      - DataBase/MySQL/MySQL 主从.md
    - "Redis":
        - DataBase/Redis/Redis 安装.md
        - DataBase/Redis/Redis 数据结构.md
    - "达梦":
        - DataBase/DM/达梦 Tips.md
        - DataBase/DM/达梦安装.md
        - DataBase/DM/达梦备份.md
    - "Doris":
        - DataBase/Doris/Doris Tips.md
        - DataBase/Doris/Doris 动态分区.md
        - DataBase/Doris/Doris 接入 Kafka 的数据.md
        - DataBase/Doris/Doris 接入 MySQL 的数据.md
  - Java:
      - Java/Java Tips.md
      - Java/Java 并发.md
      - Java/反射和动态代理.md
      - "JVM":
          - Java/JVM 内存空间划分.md
          - Java/String.intern().md
          - Java/JVM 命令行工具.md
      - "MyBatis":
          - MyBatis/MyBatis 快速入门.md
          - MyBatis/MyBatis 反射工具箱.md
          - MyBatis/MyBatis 日志模块.md
      - "Spring":
          - Spring/Spring Tips.md
          - Spring/日期时间序列化.md
  - 运维:
    - "Linux":
      - Operations/Linux/Linux Tips.md
      - Operations/Linux/系统加固.md
      - Operations/Linux/fail2ban.md
      - Operations/Linux/VIM.md
      - Operations/Linux/软件安装.md
      - Operations/Linux/文件系统.md
      - Operations/Linux/磁盘挂载.md
      - Operations/Linux/定时任务.md
      - Operations/Linux/iptables.md
      - Operations/Linux/smb.md
    - "Nginx":
      - Operations/Nginx/Nginx Tips.md
      - Operations/Nginx/Nginx 编译安装.md
      - Operations/Nginx/Nginx 日志.md
      - Operations/Nginx/Nginx 配置 Basic Auth.md
      - Operations/Nginx/Nginx 使用自签名证书.md
    - "Docker":
      - Operations/Docker/Docker Tips.md
    - K8S:
      - Operations/K8S/安装 Kubernetes 集群.md
      - Operations/K8S/安装 Kuboard 集群管理界面.md
      - Operations/K8S/安装 Nginx Ingress.md
  - 三座大山:
    - 计算机网络:
        - ThreeMountains/Network/Network Tips.md
        - ThreeMountains/Network/网络层：IP.md
        - ThreeMountains/Network/网络层：ICMP.md
        - ThreeMountains/Network/运输层：UDP.md
        - ThreeMountains/Network/运输层：TCP.md
    - 操作系统:
        - ThreeMountains/OS/OS Tips.md
        - ThreeMountains/OS/进程.md
        - ThreeMountains/OS/线程.md
        - ThreeMountains/OS/并发控制.md
        - ThreeMountains/OS/汇编——介绍.md
        - ThreeMountains/OS/汇编——环境搭建.md
        - ThreeMountains/OS/C.md
    - 数据结构和算法:
        - ThreeMountains/Algorithms/求解算数表达式的值.md
        - ThreeMountains/Algorithms/Base64 算法.md
        - ThreeMountains/Algorithms/数据结构：图.md

  - 大数据:
    - "Kafka":
      - BigData/Kafka/Kafka 快速开始.md
      - BigData/Kafka/Kafka 常用命令.md
    - "Flink":
      - BigData/Flink/Flink Tips.md
      - BigData/Flink/Flink 快速开始.md
    - "Hadoop":
      - BigData/Hadoop/Hadoop Tips.md
      - BigData/Hadoop/Hadoop 快速开始.md
  - YOLO:
    - yolo/YOLO Tips.md
    - yolo/YOLO 环境搭建.md
    - yolo/YOLO 数据集构建与训练.md


extra_css:
  - stylesheets/extra.css
extra_javascript:
  - copy-code.js
