site_name: 陈亮的笔记
theme:
  favicon: LocalFile/favicon.svg
  logo: LocalFile/favicon.svg
  palette: 
    primary: custom
  font:
    text: FangSong
    code: Consolas
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.select
  language: zh
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


nav:
  - 数据库:
    - "MySQL":
      - MySQL/MySQL Tips.md
      - MySQL/MySQL 系统和状态变量.md
      - MySQL/MySQL 安装.md
      - MySQL/MySQL 备份.md
      - MySQL/MySQL 配置主从.md
    - "Redis":
        - Redis/Redis 安装.md
        - Redis/Redis 数据结构.md
    - "达梦":
        - DM/达梦 Tips.md
        - DM/达梦安装.md
        - DM/达梦备份.md
    - "Doris":
        - Doris/Doris Tips.md
        - Doris/Doris 接入 Kafka 的数据.md
        - Doris/Doris 接入 MySQL 的数据.md
  - K8S:
      - K8S/安装 Kubernetes 集群.md
      - K8S/安装 Kuboard 集群管理界面.md
      - K8S/安装 Nginx Ingress.md
  - Linux:
    - Linux/Linux Tips.md
    - Linux/正则表达式.md
    - Linux/查找文件.md
    - Linux/ArcLinux 安装.md
    - Linux/curl.md
    - Linux/Debian 软件安装.md
    - Linux/Git.md
    - Linux/iptables.md
    - Linux/磁盘分区.md
    - Linux/Linux 定时任务.md
    - Linux/Linux 文件系统.md
    - Linux/Linux 账号群组.md
    - Linux/ls.md
    - "Nginx":
      - Linux/Nginx Tips.md
      - Linux/Nginx 编译安装.md
      - Linux/Nginx 配置 Basic Auth.md
      - Linux/Nginx 使用自签名证书.md
    - Linux/PT.md
    - Linux/Shell 脚本.md
    - Linux/VIM.md

    - Linux/时间.md
    - Linux/运维监控.md

  - 计算机网络:
      - Network/Network Tips.md
      - Network/网络层：IP.md
      - Network/网络层：ICMP.md
      - Network/运输层：UDP.md
      - Network/运输层：TCP.md
  - 操作系统:
      - OS/OS Tips.md
      - OS/进程.md
      - OS/线程.md
      - OS/并发控制.md
      - OS/汇编——介绍.md
      - OS/汇编——环境搭建.md
      - OS/C.md
  - 数据结构和算法:
      - Algorithms/求解算数表达式的值.md
      - Algorithms/Base64 算法.md
      - Algorithms/数据结构：图.md
#  - Architecture:
#      - Architecture/设备信息.md
  - 爪哇:
    - Java/Java Tips.md
    - Java/Java 并发.md
    - Java/重复提交.md
    - Java/反射和动态代理.md
    - "JVM":
      - Java/JVM 内存空间划分.md
      - Java/String.intern().md
      - Java/JVM 命令行工具.md
    - "MyBatis":
      - Java/MyBatis 快速入门.md
  - 大数据:
    - "Kafka":
      - Kafka/Kafka 快速开始.md
      - Kafka/Kafka 常用命令.md
  - 文章:
      - Arts/满江红-岳飞.md
      - Arts/侠客行-李白.md
      - Arts/大观楼长联-孙髯.md

  # - 记录:
  #     - Reading/Timeline.md
  #     - Reading/2022.md
  #     - Reading/2021.md
  #     - Reading/2023.md

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - copy-code.js
